apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::817084543485:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J3V05WSRAFBA
      username: system:node:{{EC2PrivateDNSName}}

    - groups:
      - system:masters
      rolearn: arn:aws:iam::817084543485:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T18:14:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8075"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 81a2d836-9892-4a9c-95e9-fa7d49ff0ff0
